title: "Sentiment Analysis â€” Justice John Paul Stevens Authored Opinions"
description: "A Jekyll site"
theme: minima
markdown: kramdown
exclude:
  - "*.Rmd"
  - "*.R"
  - "*.Rproj"
  - "renv/"
  - "renv.lock"
